backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "housing model"
        name: "housing model"
        file: "content/housingmodel.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Index"
        name: "Index"
        file: "content/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Description, name: description, widget: string}
          - {label: Text Header, name: topheading, widget: string}
          - {label: Video Image, name: video_thumbnail, widget: image`}
          - {label: Youtube, name: youtube, widget: string}
