backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: "founders"
    label: "founders"
    folder: "content/founders-content"
    create: true
    fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name:"body", widget:"markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "Index"
        file: "content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text Header, name: topheading, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Description, name: description, widget: string}
          - {label: Video Image, name: video_thumbnail, widget: image}
          - {label: Youtube Link, name: youtube, widget: string}
      - label: "housing Model"
        name: "housingmodel"
        file: "content/housingmodel.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text Header, name: topheading, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Description, name: description, widget: string}
